version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: lighthouse_qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage:z
    restart: unless-stopped
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334

# WILL USE THIS PART LATER
  # backend:
  #   build: ./backend
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - qdrant
  #   environment:
  #     - QDRANT_HOST=qdrant
  #     - QDRANT_PORT=6333
  

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend